output: "/home/srivastavaa/avi/bingzie/flash/workflow/k27me3"
temp: "/home/srivastavaa/avi/bingzie/flash/workflow/temp"
flash_bin: "/home/srivastavaa/avi/bingzie/flash/src-rs/target/release/flash"
threads: 10
reads:
  r1:
    - "/home/srivastavaa/avi/bingzie/k27me3/scPBMC_K27me3_BJ135_1_S1_L001_R1_001.fastq.gz"
    - "/home/srivastavaa/avi/bingzie/k27me3/scPBMC_K27me3_BJ135_1_S1_L002_R1_001.fastq.gz"
    - "/home/srivastavaa/avi/bingzie/k27me3/scPBMC_K27me3_BJ135_1_S1_L003_R1_001.fastq.gz"
    - "/home/srivastavaa/avi/bingzie/k27me3/scPBMC_K27me3_BJ135_1_S1_L004_R1_001.fastq.gz"
  r2:
    - "/home/srivastavaa/avi/bingzie/k27me3/scPBMC_K27me3_BJ135_1_S1_L001_R2_001.fastq.gz"
    - "/home/srivastavaa/avi/bingzie/k27me3/scPBMC_K27me3_BJ135_1_S1_L002_R2_001.fastq.gz"
    - "/home/srivastavaa/avi/bingzie/k27me3/scPBMC_K27me3_BJ135_1_S1_L003_R2_001.fastq.gz"
    - "/home/srivastavaa/avi/bingzie/k27me3/scPBMC_K27me3_BJ135_1_S1_L004_R2_001.fastq.gz"
  r3:
    - "/home/srivastavaa/avi/bingzie/k27me3/scPBMC_K27me3_BJ135_1_S1_L001_R3_001.fastq.gz"
    - "/home/srivastavaa/avi/bingzie/k27me3/scPBMC_K27me3_BJ135_1_S1_L002_R3_001.fastq.gz"
    - "/home/srivastavaa/avi/bingzie/k27me3/scPBMC_K27me3_BJ135_1_S1_L003_R3_001.fastq.gz"
    - "/home/srivastavaa/avi/bingzie/k27me3/scPBMC_K27me3_BJ135_1_S1_L004_R3_001.fastq.gz"
      #  r1:
      #    - "/home/srivastavaa/avi/bingzie/k27ac/scPBMC_K27ac_BJ134_1_S1_L001_R1_001.fastq.gz"
      #    - "/home/srivastavaa/avi/bingzie/k27ac/scPBMC_K27ac_BJ134_1_S1_L002_R1_001.fastq.gz"
      #    - "/home/srivastavaa/avi/bingzie/k27ac/scPBMC_K27ac_BJ134_1_S1_L003_R1_001.fastq.gz"
      #    - "/home/srivastavaa/avi/bingzie/k27ac/scPBMC_K27ac_BJ134_1_S1_L004_R1_001.fastq.gz"
      #  r2: 
      #    - "/home/srivastavaa/avi/bingzie/k27ac/scPBMC_K27ac_BJ134_1_S1_L001_R2_001.fastq.gz"
      #    - "/home/srivastavaa/avi/bingzie/k27ac/scPBMC_K27ac_BJ134_1_S1_L002_R2_001.fastq.gz"
      #    - "/home/srivastavaa/avi/bingzie/k27ac/scPBMC_K27ac_BJ134_1_S1_L003_R2_001.fastq.gz"
      #    - "/home/srivastavaa/avi/bingzie/k27ac/scPBMC_K27ac_BJ134_1_S1_L004_R2_001.fastq.gz"
      #  r3: 
      #    - "/home/srivastavaa/avi/bingzie/k27ac/scPBMC_K27ac_BJ134_1_S1_L001_R3_001.fastq.gz"
      #    - "/home/srivastavaa/avi/bingzie/k27ac/scPBMC_K27ac_BJ134_1_S1_L002_R3_001.fastq.gz"
      #    - "/home/srivastavaa/avi/bingzie/k27ac/scPBMC_K27ac_BJ134_1_S1_L003_R3_001.fastq.gz"
      #    - "/home/srivastavaa/avi/bingzie/k27ac/scPBMC_K27ac_BJ134_1_S1_L004_R3_001.fastq.gz"
