Sample
        r1: "/home/srivastavaa/avi/bingzie/scPBMC_K27ac_BJ134_1_S1_L001_R1_001.fastq.gz"
        r2: "/home/srivastavaa/avi/bingzie/scPBMC_K27ac_BJ134_1_S1_L001_R2_001.fastq.gz"
        r3: "/home/srivastavaa/avi/bingzie/scPBMC_K27ac_BJ134_1_S1_L001_R3_001.fastq.gz"
