output: "/gpfs/commons/home/asrivastava/flash/output"
temp: "/gpfs/commons/home/asrivastava/flash/temp"
flash_bin: "/gpfs/commons/home/asrivastava/flash/src-rs/target/release/flash"
bwa_mem2_bin: "/gpfs/commons/home/asrivastava/miniconda3/envs/snakemake/bin/bwa"
samtools_bin: "samtools"
atac_10x_whitelist: "/gpfs/commons/home/asrivastava/flash/index/737K-cratac-v1.txt"
threads: 10
reads:
  r1:
    - "/gpfs/commons/home/asrivastava/flash/reads/atac_pbmc_1k_v1_S1_L001_R1_001.fastq.gz"
    #- "/gpfs/commons/home/asrivastava/flash/reads/atac_pbmc_1k_v1_S1_L002_R1_001.fastq.gz"
  r2:
    - "/gpfs/commons/home/asrivastava/flash/reads/atac_pbmc_1k_v1_S1_L001_R2_001.fastq.gz"
    #- "/gpfs/commons/home/asrivastava/flash/reads/atac_pbmc_1k_v1_S1_L002_R1_001.fastq.gz"
  r3:
    - "/gpfs/commons/home/asrivastava/flash/reads/atac_pbmc_1k_v1_S1_L001_R1_001.fastq.gz"
    #- "/gpfs/commons/home/asrivastava/flash/reads/atac_pbmc_1k_v1_S1_L002_R3_001.fastq.gz"
