output: "/home/srivastavaa/avi/bingzie/flash/workflow/output"
temp: "/home/srivastavaa/avi/bingzie/flash/workflow/temp"
threads: 10
reads:
  r1: "/home/srivastavaa/avi/bingzie/k27ac/scPBMC_K27ac_BJ134_1_S1_L001_R1_001.fastq.gz"
  r2: "/home/srivastavaa/avi/bingzie/k27ac/scPBMC_K27ac_BJ134_1_S1_L001_R2_001.fastq.gz"
  r3: "/home/srivastavaa/avi/bingzie/k27ac/scPBMC_K27ac_BJ134_1_S1_L001_R3_001.fastq.gz"
